### ISSUE TITLE
Dapr 1.13 Operator Upgrade

### ISSUE THREAD

**Issue by ryorke1** [dapr-sandbox/dapr-kubernetes-operator#107]
Hello, 

Is there a timeline for releasing the operator to support 1.13.0?

**Comment by lburgazzoli** [comment]
hopefully I have some time this week

**Comment by ryorke1** [comment]
Hi @lburgazzoli. Any updates? Is there anyway I can assist with this?

**Comment by lburgazzoli** [comment]
looking into this right now, I'll be traveling tomorrow but I should have something by end of the week or beginning next week

**Comment by lburgazzoli** [comment]
PR Opened https://github.com/dapr-sandbox/dapr-kubernetes-operator/pull/109

**Comment by ryorke1** [comment]
Thank you @lburgazzoli

**Comment by ryorke1** [comment]
Hi @lburgazzoli have you had a chance to submit the PR for 0.0.6? I have been monitoring the operator hub repo but I am not seeing any PR for this new version.

**Comment by lburgazzoli** [comment]
> Hi @lburgazzoli have you had a chance to submit the PR for 0.0.6? I have been monitoring the operator hub repo but I am not seeing any PR for this new version.

on it right now

**Comment by lburgazzoli** [comment]
@ryorke1 both the PR have been merged
