### ISSUE TITLE
Missing tabs for CRDs in v0.0.6 release

### ISSUE THREAD

**Issue by ryorke1** [dapr-sandbox/dapr-kubernetes-operator#115]
Hi @lburgazzoli 

After the release, we noticed that a number of the tabs that were previously available in v0.0.5 are no longer available in v0.0.6. I can confirm that the CRDs do exist so we can still create them via oc however it would be great to have the tabs back. 

Is this something we can get back? I have provided some screenshots as well

v0.0.5:
![image](https://github.com/dapr-sandbox/dapr-kubernetes-operator/assets/131220974/91d3850f-4c61-497c-8421-e8cacd47f5b6)

v0.0.6:
![image](https://github.com/dapr-sandbox/dapr-kubernetes-operator/assets/131220974/09c6a2d4-ca37-4d5d-bc10-dd5691963fc3)

**Comment by lburgazzoli** [comment]
this is a consequence of https://github.com/dapr-sandbox/dapr-kubernetes-operator/issues/46. Since CRSs now are installed as part of the daprninstance deployment, then they won't be visible in the tabs.

@salaboy @ItalyPaleAle ^^

**Comment by ryorke1** [comment]
Thanks @lburgazzoli
