### ISSUE TITLE
Dapr 1.13.2 upgrade - includes fixes for pubsub 

### ISSUE THREAD

**Issue by adrienndikumana** [dapr-sandbox/dapr-kubernetes-operator#117]
Hi @lburgazzoli, 

New release of [v1.13.2 includes major fixes](https://github.com/dapr/dapr/releases/tag/v1.13.2) for Dapr pubsub and other important improvements. Is there a timeline for new Kubernetes operator release for Dapr version 1.13.2? 

Thanks,
Adrien

**Comment by lburgazzoli** [comment]
Just opened https://github.com/dapr-sandbox/dapr-kubernetes-operator/pull/118
Once merged, I can move forward to trigger a release and publication to the operator hub and marketplaces.

**Comment by lburgazzoli** [comment]
I set the supported version from 4.13-4.15 as 4.12 full support ended in 2023 https://access.redhat.com/support/policy/updates/openshift

I can add support for some more version, @salaboy wdyt ?

**Comment by adrienndikumana** [comment]
@lburgazzoli @salaboy, 

I believe it makes sense to set supported versions to versions that are fully supported by RedHat. However, from my experience, many teams or individuals may not upgrade their clusters until the end of maintenance has reached. And, in some case, extended support may come in play as well.

**Comment by salaboy** [comment]
@lburgazzoli I agree with @adrienndikumana it might be great to cover a wide range of supported versions, but how much work will this add on the operator side? I just adding that to the matrix of supported version so the operator is tested against those versions?

**Comment by lburgazzoli** [comment]
I'm going to release a new version but the end of the week

**Comment by lburgazzoli** [comment]
FYI, it is taking some more time than expected as I found some issues with the range selection and the openshift release pipeline is having issues at the moment.

**Comment by lburgazzoli** [comment]
dapr-kubernetes-operator v0.0.8 is now available on all the operator hubs: 

![image](https://github.com/dapr-sandbox/dapr-kubernetes-operator/assets/1868933/4e7dc341-9296-47f4-8314-4a6ad71ac65f)
![image](https://github.com/dapr-sandbox/dapr-kubernetes-operator/assets/1868933/4847d99c-ea21-4455-8766-65ace3c593ad)

**Comment by lburgazzoli** [comment]
@adrienndikumana let me know if it fixes the issue

**Comment by lburgazzoli** [comment]
@adrienndikumana closing this as the new release has been published, feel free to reopen in case something is missing

**Comment by adrienndikumana** [comment]
Thanks @lburgazzoli! Yes, I can confirm the new release is available in OpenShift 4.12 as well.

**Comment by salaboy** [comment]
thanks @lburgazzoli !
