### ISSUE TITLE
[Feature request] Allow deploying the "daprsystem" Configuration resource using the CRD

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr-sandbox/dapr-kubernetes-operator#47]
> This is based on #45

If we use a CRD with strictly-defined fields in the spec, we could also leverage that to build and deploy the Dapr Configuration resource named "daprsystem", which is used to configure the behavior of the Dapr control plane services at runtime.

https://docs.dapr.io/operations/configuration/configuration-overview/#control-plane-configuration

**Comment by salaboy** [comment]
@ItalyPaleAle is this already covered then? Do you think that is enough or do you have more requirements in mind?

**Comment by ItalyPaleAle** [comment]
That is true. It's missing a bunch of options (such as Sentry validator configuration), but looks like it's there. That's an issue for the Dapr OSS project however.
