### ISSUE TITLE
integration testing app definition

### ISSUE THREAD

**Issue by salaboy** [dapr-sandbox/dapr-kubernetes-operator#6]
We can create a testing app to validate that the operator is working and an Dapr application work with the DaprControlPlane installed by the operator. 
To check this I would create the following resources:
- Dapr Statestore and Dapr PubSub Component (optionally a Dapr Subscription) 
- A Dapr application (like this one [dapr app](https://github.com/salaboy/prototype-apps/tree/main/protoapp))
  - a container that uses the Go Dapr SDK to interact with the Statestore and PubSub API and exposes REST endpoints that can be called by the integration tests
  - (optionally) the container should also expose an endpoint to receive subscription events.

**Comment by lburgazzoli** [comment]
got a prototype to install helm stuffs for e2e tests, having a dapr app packaged as oci artifact would be ideal
